-- ============================================================================
-- Audio Generation Feature - Database Schema Extension
-- ============================================================================
-- This migration adds support for NotebookLM-style Audio Overview generation
--
-- Instructions:
-- 1. Run this after the main schema.sql has been applied
-- 2. Go to your Supabase dashboard > SQL Editor
-- 3. Paste and run this script
-- ============================================================================

-- ============================================================================
-- AUDIO GENERATION JOBS TABLE
-- ============================================================================
-- Tracks background jobs for Audio Overview generation (NotebookLM-style podcasts)
CREATE TABLE IF NOT EXISTS audio_generation_jobs (
  id VARCHAR(100) PRIMARY KEY, -- Custom job ID like "audio_abc123"
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  source_url VARCHAR(500) NOT NULL, -- URL to article/paper
  options JSONB DEFAULT '{}', -- Generation options (targetAudience, focusArea, etc.)
  status VARCHAR(20) DEFAULT 'queued', -- queued, processing, completed, failed, cancelled
  progress JSONB DEFAULT '{"step": "queued", "percentage": 0, "message": "Queued..."}',
  audio_id VARCHAR(100), -- Link to created audio overview
  result JSONB, -- Result data (audioUrl, title, duration)
  error TEXT, -- Error message if failed
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP,

  -- Constraints
  CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'cancelled'))
);

COMMENT ON TABLE audio_generation_jobs IS 'Tracks background jobs for NotebookLM-style Audio Overview generation';
COMMENT ON COLUMN audio_generation_jobs.options IS 'JSON options: targetAudience, focusArea, duration, tone';
COMMENT ON COLUMN audio_generation_jobs.progress IS 'JSON object with step, percentage, and message';

-- ============================================================================
-- AUDIO OVERVIEWS TABLE
-- ============================================================================
-- Stores generated Audio Overviews (podcast-style audio content)
CREATE TABLE IF NOT EXISTS audio_overviews (
  id VARCHAR(100) PRIMARY KEY, -- Custom ID like "audio_xyz789"
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  job_id VARCHAR(100) REFERENCES audio_generation_jobs(id) ON DELETE SET NULL,
  title VARCHAR(500) NOT NULL, -- Podcast episode title
  description TEXT, -- Episode description
  audio_url VARCHAR(500) NOT NULL, -- URL to audio file
  duration DECIMAL(10,2), -- Duration in seconds
  duration_formatted VARCHAR(20), -- Format: "6:30" or "12:45"
  topics TEXT[], -- Array of topics covered
  key_takeaways TEXT[], -- Array of key takeaways
  dialogue JSONB, -- Full dialogue script (array of speaker turns)
  turn_count INT, -- Number of dialogue turns
  source_url VARCHAR(500) NOT NULL, -- Original content URL
  source_title VARCHAR(500), -- Title of source content
  play_count INT DEFAULT 0, -- Number of times played
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE audio_overviews IS 'Stores NotebookLM-style Audio Overviews (podcast conversations)';
COMMENT ON COLUMN audio_overviews.dialogue IS 'JSON array of dialogue turns with speaker, text, and emotion';
COMMENT ON COLUMN audio_overviews.topics IS 'Array of main topics covered in the audio';
COMMENT ON COLUMN audio_overviews.key_takeaways IS 'Array of key learning points';

-- ============================================================================
-- EXTEND DAILY LIMITS TABLE
-- ============================================================================
-- Add audio_generated column to daily_limits if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'daily_limits' AND column_name = 'audio_generated'
  ) THEN
    ALTER TABLE daily_limits ADD COLUMN audio_generated INT DEFAULT 0;
  END IF;
END $$;

COMMENT ON COLUMN daily_limits.audio_generated IS 'Number of audio overviews generated today (limit: 3/day)';

-- ============================================================================
-- EXTEND USER STATS TABLE
-- ============================================================================
-- Add audio_generated column to user_stats if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'user_stats' AND column_name = 'audio_generated'
  ) THEN
    ALTER TABLE user_stats ADD COLUMN audio_generated INT DEFAULT 0;
  END IF;
END $$;

COMMENT ON COLUMN user_stats.audio_generated IS 'Total number of audio overviews generated by user';

-- ============================================================================
-- INDEXES FOR AUDIO TABLES
-- ============================================================================

-- Audio generation jobs indexes
CREATE INDEX IF NOT EXISTS idx_audio_gen_user ON audio_generation_jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_audio_gen_status ON audio_generation_jobs(status);
CREATE INDEX IF NOT EXISTS idx_audio_gen_created ON audio_generation_jobs(created_at DESC);

-- Audio overviews indexes
CREATE INDEX IF NOT EXISTS idx_audio_overview_user ON audio_overviews(user_id);
CREATE INDEX IF NOT EXISTS idx_audio_overview_created ON audio_overviews(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audio_overview_source ON audio_overviews(source_url);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Apply update_updated_at trigger to audio tables
DROP TRIGGER IF EXISTS update_audio_gen_updated_at ON audio_generation_jobs;
CREATE TRIGGER update_audio_gen_updated_at
  BEFORE UPDATE ON audio_generation_jobs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_audio_overview_updated_at ON audio_overviews;
CREATE TRIGGER update_audio_overview_updated_at
  BEFORE UPDATE ON audio_overviews
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- VERIFICATION
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE '✅ Audio Overview schema migration completed!';
    RAISE NOTICE '';
    RAISE NOTICE '📋 New tables created:';
    RAISE NOTICE '   - audio_generation_jobs (tracks audio generation jobs)';
    RAISE NOTICE '   - audio_overviews (stores generated podcast-style audio)';
    RAISE NOTICE '';
    RAISE NOTICE '🔄 Updated tables:';
    RAISE NOTICE '   - daily_limits (added audio_generated column)';
    RAISE NOTICE '   - user_stats (added audio_generated column)';
    RAISE NOTICE '';
    RAISE NOTICE '🎙️ Audio Overview Feature Ready!';
    RAISE NOTICE '   Similar to NotebookLM Audio Overviews';
    RAISE NOTICE '   Generates podcast-style conversations from content';
END $$;

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
