const express = require('express');
const { body, query } = require('express-validator');
const {
  getAllVideos,
  searchVideos,
  getMyVideos,
  getBookmarkedVideos,
  getVideoById,
  bookmarkVideo,
  removeBookmark,
  incrementView
} = require('../controllers/videos.controller');
const { authenticate, optionalAuth } = require('../middleware/auth');

const router = express.Router();

/**
 * @route   GET /api/videos
 * @desc    Get all videos with optional filtering and pagination
 * @access  Public (shows bookmark status if authenticated)
 * @query   category, search, page, limit
 */
router.get(
  '/',
  optionalAuth, // Optional authentication to show bookmark status
  [
    query('category').optional().isString(),
    query('search').optional().isString(),
    query('page').optional().isInt({ min: 1 }).toInt(),
    query('limit').optional().isInt({ min: 1, max: 100 }).toInt()
  ],
  getAllVideos
);

/**
 * @route   GET /api/videos/search
 * @desc    Search videos by query
 * @access  Public
 * @query   q (search query), category
 */
router.get(
  '/search',
  optionalAuth,
  [
    query('q').notEmpty().withMessage('Search query is required'),
    query('category').optional().isString()
  ],
  searchVideos
);

/**
 * @route   GET /api/videos/my-videos
 * @desc    Get videos generated by the authenticated user
 * @access  Private
 */
router.get('/my-videos', authenticate, getMyVideos);

/**
 * @route   GET /api/videos/bookmarks
 * @desc    Get user's bookmarked videos
 * @access  Private
 */
router.get('/bookmarks', authenticate, getBookmarkedVideos);

/**
 * @route   GET /api/videos/:id
 * @desc    Get a single video by ID
 * @access  Public (bookmark status if authenticated)
 */
router.get('/:id', optionalAuth, getVideoById);

/**
 * @route   POST /api/videos/:id/bookmark
 * @desc    Bookmark a video
 * @access  Private
 */
router.post('/:id/bookmark', authenticate, bookmarkVideo);

/**
 * @route   DELETE /api/videos/:id/bookmark
 * @desc    Remove bookmark from a video
 * @access  Private
 */
router.delete('/:id/bookmark', authenticate, removeBookmark);

/**
 * @route   POST /api/videos/:id/view
 * @desc    Increment view count for a video
 * @access  Public
 */
router.post(
  '/:id/view',
  optionalAuth,
  [
    body('watchDuration')
      .optional()
      .isInt({ min: 0 })
      .withMessage('Watch duration must be a positive integer')
  ],
  incrementView
);

module.exports = router;
